// Roseriser Web Application
// Browser-compatible DXF converter GUI

import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { STLExporter } from 'three/addons/exporters/STLExporter.js';
import {
    f_o_sketch_from_o_dxf,
    f_s_scad_path_sweep_sketch,
    f_s_scad_profile_functions_from_o_sketch
} from './manual.module.h.js';

// ============ API FUNCTIONS ============

/**
 * Call server API to parse DXF file
 * @param {string} dxfText - The DXF file content as string
 * @returns {Promise<object>} - Parsed DXF data from server
 */
async function parseDxfViaApi(dxfText) {
    const response = await fetch('/api/parse-dxf', {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        body: dxfText
    });

    if (!response.ok) {
        const err = await response.json();
        throw new Error(err.error || 'Failed to parse DXF');
    }

    return await response.json();
}

// ============ YOUR CONVERSION FUNCTIONS ============
// Add your DXF to SCAD/SVG conversion code here

/**
 * Convert DXF string to sketch object
 * Called after file upload - sends DXF to server for parsing
 * @param {string} s_dxf - The DXF file content as string
 * @returns {Promise<object>} - Your sketch object
 */
async function convertDxfToSketch(s_dxf) {
    // Step 1: Parse DXF via server API
    const o_dxf = await parseDxfViaApi(s_dxf);

    let o_sketch = await f_o_sketch_from_o_dxf(o_dxf);
    return o_sketch;
    // Step 2: Convert parsed DXF to your sketch format
    // TODO: Add your conversion logic here
    // parsedDxf contains: { entities: [...], tables: {...}, blocks: {...}, ... }
    // Each entity has: type (LINE, ARC, CIRCLE, etc.), and type-specific properties

    // For now, return the raw parsed data - replace with your conversion
    // return parsedDxf;
}

/**
 * Generate SVG string from sketch object
 * @param {object} sketch - The sketch object from convertDxfToSketch
 * @returns {string} - SVG markup string
 */
function generateSvgFromSketch(sketch) {
    // sketch.s_svg is generated by f_o_sketch_from_s_dxf
    return sketch.s_svg || '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text x="10" y="50">No SVG</text></svg>';
}

/**
 * Generate SCAD string from sketches
 * @param {object} sketchPath - The main sketch/path object
 * @param {string} sketchPathName - Name for the sketch in SCAD
 * @param {object} sketchProfile - The profile sketch object
 * @param {string} sketchProfileName - Name for the profile in SCAD
 * @param {object} sketchRemover - The remover profile sketch object
 * @param {string} sketchRemoverName - Name for the remover in SCAD
 * @returns {string} - OpenSCAD code string
 */
function generateScadFromSketches(sketchPath, sketchPathName, sketchProfile, sketchProfileName, sketchRemover, sketchRemoverName) {
    return f_s_scad_path_sweep_sketch(
        sketchPath, sketchPathName,
        sketchProfile, sketchProfileName,
        sketchRemover, sketchRemoverName
    );
}

/**
 * Render 3D preview from sketches (optional - for Three.js viewer)
 * @param {object} sketchPath - The main sketch/path object
 * @param {object} sketchProfile - The profile sketch object
 * @param {number} scale - Scale factor
 */
function render3DFromSketches(sketchPath, sketchProfile, scale) {
    // TODO: Add your 3D rendering logic here if you want to use the Three.js viewer
    // Use threeViewer.scene to add meshes, threeViewer.meshes array to track them
    console.log('3D rendering not implemented');
}

// ============ THREE.JS 3D VIEWER ============

const threeViewer = {
    scene: null,
    camera: null,
    renderer: null,
    controls: null,
    meshes: [],
    wireframe: false,
    scale: 0.5,

    init() {
        const container = document.getElementById('threejs-container');
        const rect = container.getBoundingClientRect();

        // Scene
        this.scene = new THREE.Scene();
        this.scene.background = new THREE.Color(0x222222);

        // Camera
        this.camera = new THREE.PerspectiveCamera(45, rect.width / rect.height, 0.1, 10000);
        this.camera.position.set(100, 100, 100);

        // Renderer
        this.renderer = new THREE.WebGLRenderer({ antialias: true });
        this.renderer.setPixelRatio(window.devicePixelRatio);
        this.renderer.setSize(rect.width, rect.height);
        container.appendChild(this.renderer.domElement);

        // Controls
        this.controls = new OrbitControls(this.camera, this.renderer.domElement);
        this.controls.enableDamping = true;
        this.controls.dampingFactor = 0.05;

        // Lights
        const ambientLight = new THREE.AmbientLight(0x404040, 2);
        this.scene.add(ambientLight);

        const directionalLight = new THREE.DirectionalLight(0xffffff, 1);
        directionalLight.position.set(100, 100, 100);
        this.scene.add(directionalLight);

        const directionalLight2 = new THREE.DirectionalLight(0xffffff, 0.5);
        directionalLight2.position.set(-100, -100, -100);
        this.scene.add(directionalLight2);

        // Grid helper
        const gridHelper = new THREE.GridHelper(200, 20, 0x444444, 0x333333);
        gridHelper.rotation.x = Math.PI / 2;
        this.scene.add(gridHelper);

        // Axes helper
        const axesHelper = new THREE.AxesHelper(50);
        this.scene.add(axesHelper);

        // Animation loop
        const animate = () => {
            requestAnimationFrame(animate);
            this.controls.update();
            this.renderer.render(this.scene, this.camera);
        };
        animate();

        // Resize handler
        window.addEventListener('resize', () => this.onResize());

        // Toolbar buttons
        document.getElementById('reset-camera').addEventListener('click', () => this.resetCamera());
        document.getElementById('toggle-wireframe').addEventListener('click', () => this.toggleWireframe());
        document.getElementById('scale-slider').addEventListener('input', (e) => {
            this.scale = parseFloat(e.target.value);
            document.getElementById('scale-value').textContent = this.scale.toFixed(1);
            this.updateMeshes();
        });
    },

    onResize() {
        const container = document.getElementById('threejs-container');
        const rect = container.getBoundingClientRect();
        this.camera.aspect = rect.width / rect.height;
        this.camera.updateProjectionMatrix();
        this.renderer.setSize(rect.width, rect.height);
    },

    resetCamera() {
        this.camera.position.set(100, 100, 100);
        this.camera.lookAt(0, 0, 0);
        this.controls.reset();
    },

    toggleWireframe() {
        this.wireframe = !this.wireframe;
        this.meshes.forEach(mesh => {
            if (mesh.material) mesh.material.wireframe = this.wireframe;
        });
    },

    clearMeshes() {
        this.meshes.forEach(mesh => {
            this.scene.remove(mesh);
            if (mesh.geometry) mesh.geometry.dispose();
            if (mesh.material) mesh.material.dispose();
        });
        this.meshes = [];
    },

    updateMeshes() {
        if (!state.sketches.sketch || !state.sketches.profile) return;
        this.clearMeshes();
        render3DFromSketches(state.sketches.sketch, state.sketches.profile, this.scale);
    },

    fitCameraToScene() {
        if (this.meshes.length === 0) return;

        const box = new THREE.Box3();
        this.meshes.forEach(mesh => box.expandByObject(mesh));

        const center = box.getCenter(new THREE.Vector3());
        const size = box.getSize(new THREE.Vector3());
        const maxDim = Math.max(size.x, size.y, size.z);

        this.camera.position.set(
            center.x + maxDim,
            center.y + maxDim,
            center.z + maxDim
        );
        this.camera.lookAt(center);
        this.controls.target.copy(center);
    },

    exportSTL() {
        if (this.meshes.length === 0) {
            console.warn('No meshes to export');
            return null;
        }

        const group = new THREE.Group();
        this.meshes.forEach(mesh => {
            const clonedMesh = mesh.clone();
            group.add(clonedMesh);
        });

        const exporter = new STLExporter();
        return exporter.parse(group, { binary: false });
    },

    exportSTLBinary() {
        if (this.meshes.length === 0) {
            console.warn('No meshes to export');
            return null;
        }

        const group = new THREE.Group();
        this.meshes.forEach(mesh => {
            const clonedMesh = mesh.clone();
            group.add(clonedMesh);
        });

        const exporter = new STLExporter();
        return exporter.parse(group, { binary: true });
    }
};

// Make threeViewer available globally for custom render functions
globalThis.threeViewer = threeViewer;

// ============ APPLICATION STATE ============

const state = {
    files: { sketch: null, profile: null, remover: null },
    sketches: { sketch: null, profile: null, remover: null },
    outputs: { svg: '', scad: '', json: '' },
    editor: null,
    currentTab: 'scad',
    currentView: 'svg'
};
globalThis.state = state;

// ============ SVG PAN/ZOOM ============

// Factory function to create SVG viewer for a panel
function createSvgViewer(containerId, wrapperId, headerId) {
    return {
        scale: 1,
        translateX: 0,
        translateY: 0,
        isDragging: false,
        lastX: 0,
        lastY: 0,
        containerId,
        wrapperId,
        headerId,

        init() {
            const container = document.getElementById(this.containerId);
            if (!container) return;

            container.addEventListener('wheel', (e) => {
                e.preventDefault();
                const delta = e.deltaY > 0 ? 0.9 : 1.1;
                const rect = container.getBoundingClientRect();
                const x = e.clientX - rect.left;
                const y = e.clientY - rect.top;

                const newScale = Math.max(0.1, Math.min(10, this.scale * delta));
                const scaleChange = newScale / this.scale;

                this.translateX = x - (x - this.translateX) * scaleChange;
                this.translateY = y - (y - this.translateY) * scaleChange;
                this.scale = newScale;
                this.updateTransform();
            });

            container.addEventListener('mousedown', (e) => {
                this.isDragging = true;
                this.lastX = e.clientX;
                this.lastY = e.clientY;
            });

            container.addEventListener('mousemove', (e) => {
                if (!this.isDragging) return;
                this.translateX += e.clientX - this.lastX;
                this.translateY += e.clientY - this.lastY;
                this.lastX = e.clientX;
                this.lastY = e.clientY;
                this.updateTransform();
            });

            container.addEventListener('mouseup', () => { this.isDragging = false; });
            container.addEventListener('mouseleave', () => { this.isDragging = false; });
        },

        updateTransform() {
            const wrapper = document.getElementById(this.wrapperId);
            if (wrapper) {
                wrapper.style.transform = `translate(${this.translateX}px, ${this.translateY}px) scale(${this.scale})`;
            }
        },

        fitToContainer() {
            const container = document.getElementById(this.containerId);
            const wrapper = document.getElementById(this.wrapperId);
            if (!container || !wrapper) return;
            const svg = wrapper.querySelector('svg');
            if (!svg) return;

            // Reset first
            this.scale = 1;
            this.translateX = 0;
            this.translateY = 0;
            this.updateTransform();

            // Calculate fit
            setTimeout(() => {
                const containerRect = container.getBoundingClientRect();
                const svgRect = svg.getBoundingClientRect();
                if (svgRect.width === 0 || svgRect.height === 0) return;

                const scaleX = (containerRect.width - 20) / svgRect.width;
                const scaleY = (containerRect.height - 20) / svgRect.height;
                this.scale = Math.min(scaleX, scaleY, 2);

                this.translateX = (containerRect.width - svgRect.width * this.scale) / 2;
                this.translateY = (containerRect.height - svgRect.height * this.scale) / 2;
                this.updateTransform();
            }, 50);
        },

        reset() {
            this.scale = 1;
            this.translateX = 0;
            this.translateY = 0;
            this.updateTransform();
        },

        setSVG(svgString) {
            const wrapper = document.getElementById(this.wrapperId);
            const header = document.getElementById(this.headerId);
            if (!wrapper) return;

            wrapper.innerHTML = svgString;
            const svg = wrapper.querySelector('svg');
            if (svg) {
                svg.style.width = 'auto';
                svg.style.height = 'auto';
                svg.style.maxWidth = '100%';
                svg.style.maxHeight = '100%';
            }
            if (header) {
                header.classList.add('loaded');
            }
            setTimeout(() => this.fitToContainer(), 100);
        }
    };
}

// Create viewer for sketch panel (top)
const sketchViewer = createSvgViewer('svg-container-sketch', 'svg-wrapper-sketch', 'header-sketch');

// Create viewer for profile panel (bottom) with overlay support
const profileViewer = {
    ...createSvgViewer('svg-container-profile', 'svg-wrapper-profile', 'header-profile'),

    // Override updateTransform to also update remover overlay
    updateTransform() {
        const profileWrapper = document.getElementById('svg-wrapper-profile');
        const removerWrapper = document.getElementById('svg-wrapper-remover');
        const transform = `translate(${this.translateX}px, ${this.translateY}px) scale(${this.scale})`;
        if (profileWrapper) profileWrapper.style.transform = transform;
        if (removerWrapper) removerWrapper.style.transform = transform;
    },

    setRemoverSVG(svgString) {
        const wrapper = document.getElementById('svg-wrapper-remover');
        const header = document.getElementById('header-remover');
        if (!wrapper) return;

        wrapper.innerHTML = svgString;
        const svg = wrapper.querySelector('svg');
        if (svg) {
            svg.style.width = 'auto';
            svg.style.height = 'auto';
        }
        if (header) {
            header.classList.add('loaded');
        }
        // Apply current transform to keep in sync
        this.updateTransform();
    }
};

// Initialize all viewers and toolbar buttons
function initSvgViewers() {
    sketchViewer.init();
    profileViewer.init();

    // Toolbar buttons affect both panels
    document.getElementById('zoom-in').addEventListener('click', () => {
        sketchViewer.scale *= 1.2; sketchViewer.updateTransform();
        profileViewer.scale *= 1.2; profileViewer.updateTransform();
    });
    document.getElementById('zoom-out').addEventListener('click', () => {
        sketchViewer.scale /= 1.2; sketchViewer.updateTransform();
        profileViewer.scale /= 1.2; profileViewer.updateTransform();
    });
    document.getElementById('zoom-reset').addEventListener('click', () => {
        sketchViewer.reset();
        profileViewer.reset();
    });
    document.getElementById('zoom-fit').addEventListener('click', () => {
        sketchViewer.fitToContainer();
        profileViewer.fitToContainer();
    });
}

// ============ MONACO EDITOR ============

function initMonaco() {
    return new Promise((resolve) => {
        require.config({ paths: { vs: 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.45.0/min/vs' } });
        require(['vs/editor/editor.main'], function () {
            state.editor = monaco.editor.create(document.getElementById('editor-container'), {
                value: '// Upload DXF files to generate SCAD output',
                language: 'cpp',
                theme: 'vs-dark',
                automaticLayout: true,
                readOnly: true,
                minimap: { enabled: false }
            });
            resolve();
        });
    });
}

// ============ FILE HANDLING ============

function readFileAsText(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsText(file);
    });
}

async function handleFileUpload(type, file) {
    try {
        updateStatus(`Parsing ${file.name}...`);
        const text = await readFileAsText(file);
        state.files[type] = { name: file.name, text };
        state.sketches[type] = await convertDxfToSketch(text);

        updateStatus(`Loaded ${file.name}`);
        processAllFiles();
    } catch (err) {
        updateStatus(`Error loading ${file.name}: ${err.message}`);
        console.error(err);
    }
}

function processAllFiles() {
    // Generate SVG previews for each loaded sketch
    if (state.sketches.sketch) {
        const svg = generateSvgFromSketch(state.sketches.sketch);
        sketchViewer.setSVG(svg);
        state.outputs.svg = svg;
        document.getElementById('dl-svg').disabled = false;
    }
    if (state.sketches.profile) {
        profileViewer.setSVG(generateSvgFromSketch(state.sketches.profile));
    }
    if (state.sketches.remover) {
        profileViewer.setRemoverSVG(generateSvgFromSketch(state.sketches.remover));
    }

    // Generate 3D preview if sketch and profile are available
    if (state.sketches.sketch && state.sketches.profile) {
        threeViewer.clearMeshes();
        render3DFromSketches(state.sketches.sketch, state.sketches.profile, threeViewer.scale);
        threeViewer.fitCameraToScene();
        document.getElementById('dl-stl').disabled = false;
    }

    // Generate JSON from all loaded sketches
    const jsonData = {};
    if (state.sketches.sketch) jsonData.sketch = state.sketches.sketch;
    if (state.sketches.profile) jsonData.profile = state.sketches.profile;
    if (state.sketches.remover) jsonData.remover = state.sketches.remover;
    state.outputs.json = JSON.stringify(jsonData, null, 2);
    document.getElementById('dl-json').disabled = !state.sketches.sketch;

    // Generate SCAD if all three files are loaded
    if (state.sketches.sketch && state.sketches.profile && state.sketches.remover) {
        const sketchName = state.files.sketch.name.replace(/\.dxf$/i, '');
        const profileName = state.files.profile.name.replace(/\.dxf$/i, '');
        const removerName = state.files.remover.name.replace(/\.dxf$/i, '');

        state.outputs.scad = generateScadFromSketches(
            state.sketches.sketch, sketchName,
            state.sketches.profile, profileName,
            state.sketches.remover, removerName
        );
        document.getElementById('dl-scad').disabled = false;
        updateStatus('All files processed - SCAD generated');
    } else if (state.sketches.sketch && state.sketches.profile) {
        const profileName = state.files.profile.name.replace(/\.dxf$/i, '');
        state.outputs.scad = f_s_scad_profile_functions_from_o_sketch(state.sketches.profile, profileName, true);
        document.getElementById('dl-scad').disabled = false;
        updateStatus('Profile loaded - upload remover for full SCAD output');
    } else if (state.sketches.sketch) {
        state.outputs.scad = '// Upload profile and profile remover DXF files to generate full SCAD output';
        updateStatus('Sketch loaded - upload profile files');
    }

    updateEditor();
}

function updateEditor() {
    if (!state.editor) return;
    const content = state.currentTab === 'scad' ? state.outputs.scad : state.outputs.json;
    const language = state.currentTab === 'scad' ? 'cpp' : 'json';
    monaco.editor.setModelLanguage(state.editor.getModel(), language);
    state.editor.setValue(content || '// No content yet');
}

function updateStatus(msg) {
    document.getElementById('status').textContent = msg;
}

// ============ VIEW SWITCHING ============

function switchView(view) {
    state.currentView = view;
    const svgPanels = document.getElementById('svg-panels');
    const threejsContainer = document.getElementById('threejs-container');
    const svgToolbar = document.getElementById('svg-toolbar');
    const threejsToolbar = document.getElementById('threejs-toolbar');

    if (view === 'svg') {
        svgPanels.classList.remove('hidden');
        threejsContainer.classList.remove('active');
        svgToolbar.style.display = 'flex';
        threejsToolbar.style.display = 'none';
    } else {
        svgPanels.classList.add('hidden');
        threejsContainer.classList.add('active');
        svgToolbar.style.display = 'none';
        threejsToolbar.style.display = 'flex';
        threeViewer.onResize();
    }
}

// ============ DOWNLOADS ============

function downloadFile(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

// ============ FILE SELECTION HANDLING ============

async function handleSelectChange(type, selectEl, fileInputEl) {
    const value = selectEl.value;

    if (value === 'custom') {
        // Trigger file input
        fileInputEl.click();
        // Reset select to show current state
        selectEl.value = '';
        return;
    }

    if (value === '') {
        return;
    }

    // Load example file
    try {
        updateStatus(`Loading ${value}...`);
        const response = await fetch(value);
        if (!response.ok) {
            throw new Error(`Failed to load ${value}`);
        }
        const text = await response.text();
        const filename = value.split('/').pop();

        state.files[type] = { name: filename, text };
        state.sketches[type] = await convertDxfToSketch(text);

        selectEl.classList.add('loaded');
        updateStatus(`Loaded ${filename}`);
        processAllFiles();
    } catch (err) {
        updateStatus(`Error: ${err.message}`);
        console.error(err);
        selectEl.value = '';
    }
}

function handleCustomFileUpload(type, file, selectEl) {
    handleFileUpload(type, file).then(() => {
        // Update select to show it's loaded with custom file
        selectEl.value = '';
        selectEl.classList.add('loaded');
    });
}

// ============ INITIALIZATION ============

document.addEventListener('DOMContentLoaded', async () => {
    await initMonaco();
    initSvgViewers();
    threeViewer.init();

    // Select dropdowns and file inputs
    const selectSketch = document.getElementById('select-sketch');
    const selectProfile = document.getElementById('select-profile');
    const selectRemover = document.getElementById('select-remover');
    const fileSketch = document.getElementById('file-sketch');
    const fileProfile = document.getElementById('file-profile');
    const fileRemover = document.getElementById('file-remover');

    // Select change handlers
    selectSketch.addEventListener('change', () => handleSelectChange('sketch', selectSketch, fileSketch));
    selectProfile.addEventListener('change', () => handleSelectChange('profile', selectProfile, fileProfile));
    selectRemover.addEventListener('change', () => handleSelectChange('remover', selectRemover, fileRemover));

    // Custom file upload handlers
    fileSketch.addEventListener('change', (e) => {
        if (e.target.files[0]) handleCustomFileUpload('sketch', e.target.files[0], selectSketch);
    });
    fileProfile.addEventListener('change', (e) => {
        if (e.target.files[0]) handleCustomFileUpload('profile', e.target.files[0], selectProfile);
    });
    fileRemover.addEventListener('change', (e) => {
        if (e.target.files[0]) handleCustomFileUpload('remover', e.target.files[0], selectRemover);
    });

    // Editor tabs
    document.querySelectorAll('.editor-tab').forEach(tab => {
        tab.addEventListener('click', () => {
            document.querySelectorAll('.editor-tab').forEach(t => t.classList.remove('active'));
            tab.classList.add('active');
            state.currentTab = tab.dataset.content;
            updateEditor();
        });
    });

    // Viewer tabs
    document.querySelectorAll('.viewer-tab').forEach(tab => {
        tab.addEventListener('click', () => {
            document.querySelectorAll('.viewer-tab').forEach(t => t.classList.remove('active'));
            tab.classList.add('active');
            switchView(tab.dataset.view);
        });
    });

    // Download buttons
    document.getElementById('dl-svg').addEventListener('click', () => {
        const name = state.files.sketch?.name.replace(/\.dxf$/i, '') || 'sketch';
        downloadFile(state.outputs.svg, `${name}.svg`, 'image/svg+xml');
    });
    document.getElementById('dl-scad').addEventListener('click', () => {
        const name = state.files.sketch?.name.replace(/\.dxf$/i, '') || 'output';
        downloadFile(state.outputs.scad, `${name}.scad`, 'text/plain');
    });
    document.getElementById('dl-json').addEventListener('click', () => {
        const name = state.files.sketch?.name.replace(/\.dxf$/i, '') || 'data';
        downloadFile(state.outputs.json, `${name}.json`, 'application/json');
    });
    document.getElementById('dl-stl').addEventListener('click', () => {
        const stlBuffer = threeViewer.exportSTLBinary();
        if (stlBuffer) {
            const name = state.files.sketch?.name.replace(/\.dxf$/i, '') || 'model';
            const blob = new Blob([stlBuffer], { type: 'application/octet-stream' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${name}.stl`;
            a.click();
            URL.revokeObjectURL(url);
        }
    });

    updateStatus('Ready - select a sketch path to begin');

    // Auto-load preselected files (profile and remover are preselected in HTML)
    if (selectProfile.value) {
        await handleSelectChange('profile', selectProfile, fileProfile);
    }
    if (selectRemover.value) {
        await handleSelectChange('remover', selectRemover, fileRemover);
    }
});
